gui_annonces_homepage:
    path:     /annonce/accueil
    defaults: { _controller: GUIAnnoncesBundle:Annonce:index }

gui_annonces_voir:
    path:     /annonce/voir
    defaults: { _controller: GUIAnnoncesBundle:Annonce:voir }

gui_formulaire_prestation:
    path:     /annonce/formulaire/prestation
    defaults: { _controller: GUIAnnoncesBundle:Annonce:formulaireprestation }